Repository jelhan/ember-autoresize-modifier, pull requests merged in 2025-03, with the labels that each got.

#212 Drop @ember/string dependency
  addon/modifiers/autoresize.js
Labels: enhancement

#214 adopt the default GitHub CI setup for Ember addons
  .github/workflows/ci.yml
Labels: internal

#217 Upgrade with Ember CLI v4.12 blueprints
  .ember-cli
  .eslintignore
  .eslintrc.js
  .gitignore
  .npmignore
  .prettierignore
  .prettierrc.js
  .stylelintignore
  .stylelintrc.js
  CONTRIBUTING.md
  README.md
  config/environment.js
  ember-cli-build.js
  package.json
  tests/dummy/app/index.html
  tests/dummy/app/styles/app.css
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/helpers/.gitkeep
  tests/helpers/index.js
  tests/index.html
  vendor/.gitkeep
  yarn.lock
Labels: internal

#219 migrate to pnpm
  .github/workflows/ci.yml
  CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  renovate.json
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  yarn.lock
Labels: internal

#215 Support Ember v5
  .github/workflows/ci.yml
  tests/dummy/config/ember-try.js
Labels: enhancement

#220 run tests against latest Ember release (v6.2) and prereleases again
  .github/workflows/ci.yml
Labels: internal

#221 run tests for Embroider again
  .github/workflows/ci.yml
Labels: internal

#223 upgrade with Ember CLI v5.12 blueprints
  .ember-cli
  .eslintignore
  .gitignore
  .npmignore
  .prettierignore
  .watchmanconfig
  CONTRIBUTING.md
  README.md
  addon/modifiers/autoresize.js
  package.json
  pnpm-lock.yaml
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/helpers/index.js
  tests/integration/modifiers/autoresize-test.js
Labels: internal

#240 upgrade with Ember CLI v6.2 blueprints
  .eslintignore
  .eslintrc.js
  .npmignore
  .prettierrc.js
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/test-helper.js
Labels: internal

#246 drop support for Ember < v4.12
  .github/workflows/ci.yml
  README.md
  package.json
  tests/dummy/config/ember-try.js
Labels: breaking
